"""add is_temporary to notes

Revision ID: ccce1f9c173a
Revises: 859d228d38ca
Create Date: 2026-03-01 17:10:43.591531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccce1f9c173a'
down_revision: Union[str, None] = '859d228d38ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_temporary', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_temporary')
    # ### end Alembic commands ###
